# Generated by Django 3.2.9 on 2021-11-18 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('docsAPI', '0002_auto_20211118_2353'),
    ]

    operations = [
        migrations.RenameField(
            model_name='msds',
            old_name='service',
            new_name='services',
        ),
    ]
