# Generated by Django 3.2.9 on 2021-11-19 16:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('docsAPI', '0003_rename_service_msds_services'),
    ]

    operations = [
        migrations.AddField(
            model_name='msds',
            name='file',
            field=models.FileField(default=1, upload_to=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='msds',
            name='services',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='msds', to='docsAPI.services'),
        ),
    ]
