# Generated by Django 3.2.9 on 2021-12-23 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docsAPI', '0006_auto_20211223_1239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='msds',
            name='file',
            field=models.FileField(blank=True, upload_to='media/'),
        ),
    ]
